package at.ac.tuwien.kr.alpha.e2etests;

import at.ac.tuwien.kr.alpha.api.Alpha;
import at.ac.tuwien.kr.alpha.api.impl.AlphaFactory;
import at.ac.tuwien.kr.alpha.api.programs.InputProgram;
import at.ac.tuwien.kr.alpha.api.programs.tests.Assertion;
import at.ac.tuwien.kr.alpha.api.programs.tests.TestResult;
import at.ac.tuwien.kr.alpha.commons.programs.Programs;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * Runs tests written in ASP from a given set of files.
 * Dynamic tests generated by this class use Alpha's default configuration.
 * A test fails when any ASP test in the corresponding fileset fails.
 */
public class End2EndTests {

	private static final String E2E_TESTS_DIR = "/e2e-tests/";

	private static void runAspTests(String testName, String... fileset) {
		Alpha alpha = AlphaFactory.newAlpha();
		Programs.InputProgramBuilder programBuilder = Programs.builder();
		for (String file : fileset) {
			try (InputStream is = End2EndTests.class.getResourceAsStream(file)) {
				programBuilder.accumulate(alpha.readProgramStream(is));
			} catch (IOException ex) {
				throw new RuntimeException("Failed to read test file: " + file, ex);
			}
		}
		InputProgram program = programBuilder.build();
		TestResult testResult = alpha.test(program);
		if (!testResult.isSuccess()) {
			StringBuilder msgBuilder = new StringBuilder("Test ").append(testName).append(" failed:").append(System.lineSeparator());
			testResult.getTestCaseResults().stream().filter(Predicate.not(TestResult.TestCaseResult::isSuccess)).forEach(tcResult -> {
				msgBuilder.append("Assertion failures for test case ").append(tcResult.getTestCaseName()).append(": ").append(System.lineSeparator());
				if (tcResult.answerSetCountVerificationResult().isPresent()) {
					msgBuilder.append(tcResult.answerSetCountVerificationResult().get()).append(System.lineSeparator());
				}
				for (Map.Entry<Assertion, List<String>> assertionError : tcResult.getAssertionErrors().entrySet()) {
					for (String errMsg : assertionError.getValue()) {
						msgBuilder.append("Assertion failed: ").append(assertionError.getKey()).append(", error = ").append(errMsg).append(System.lineSeparator());
					}
				}
			});
			fail(msgBuilder.toString());
		}
	}

	private static DynamicTest alphaEnd2EndTest(String testName, String... fileset) {
		return DynamicTest.dynamicTest(testName, () -> runAspTests(testName, fileset));
	}

	@TestFactory
	Stream<DynamicTest> alphaEnd2EndTests() {
		return Stream.of(
				alphaEnd2EndTest("3-Coloring", E2E_TESTS_DIR + "3col.asp"),
				alphaEnd2EndTest("modules-basic", E2E_TESTS_DIR + "modules-basic.evl"),
				alphaEnd2EndTest("neighboring-vertices-list", E2E_TESTS_DIR + "neighboring-vertices-list.evl"),
				alphaEnd2EndTest("bin-packing", E2E_TESTS_DIR + "bin-packing.evl", E2E_TESTS_DIR + "bin-packing.test.evl")
		);
	}

}
