name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        # We test against Java releases:
        #  - greater than or equal to 11
        #  AND
        #    - with LTS and in "Premier Support" phase
        #    OR
        #    - not succeeded by any other release
        # No Oracle JDK >11, see
        # https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later
        # https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
        java:
        # LTS and in "Premier Support" as of 2019-03 (until 2023-09)
        - 11
        # LTS as of 2021-11 (until 2029)
        - 17
        # Not succeeded as of 2022-12
        - 19
        os: [ubuntu, windows]
    env:
      # We only post coverage data for exactly one build to coveralls.
      # To pick that build from the build matrix, we designate one
      # Java version to be the "main" one.
      MAIN_JAVA: 11
      # We only post coverage data for exactly one build to coveralls.
      # To pick that build from the build matrix, we designate one
      # OS to be the "main" one.
      MAIN_OS: ubuntu
    steps:
    # See https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    # See https://github.com/marketplace/actions/gradle-wrapper-validation
    - uses: gradle/wrapper-validation-action@v1
    # See https://github.com/marketplace/actions/setup-java-jdk
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    # See https://github.com/marketplace/actions/gradle-build-action
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build --stacktrace
    - uses: gradle/gradle-build-action@v2
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
      with:
        arguments: jacocoTestReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - uses: codecov/codecov-action@v1
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
