name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        # We test against Java releases:
        #  - greater than 7
        #  AND
        #    - with LTS and in "Premier Support" phase
        #    OR
        #    - not succeeded by any other release
        # No Oracle JDK >11, see
        # https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later
        # https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
        java:
        # LTS and in "Premier Support" as of 2019-03 (until 2022-03)
        - 8
        # LTS and in "Premier Support" as of 2019-03 (until 2023-09)
        - 11
        # LTS as of 2021-11 (until 2029)
        - 17
        os: [ubuntu, windows]
    env:
      # We only post coverage data for exactly one build to coveralls.
      # To pick that build from the build matrix, we designate one
      # Java version to be the "main" one.
      MAIN_JAVA: 11
      # We only post coverage data for exactly one build to coveralls.
      # To pick that build from the build matrix, we designate one
      # OS to be the "main" one.
      MAIN_OS: ubuntu
    steps:
    # See https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    # See https://github.com/marketplace/actions/gradle-wrapper-validation
    - uses: gradle/wrapper-validation-action@v1
    # See https://github.com/marketplace/actions/setup-java-jdk
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    # See https://github.com/marketplace/actions/gradle-build-action
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build --stacktrace
    - uses: gradle/gradle-build-action@v2
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
      with:
        arguments: jacocoTestReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - uses: codecov/codecov-action@v1
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
  native-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up Graal
      run: |
        mkdir graalvm
        wget -qO- 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java17-linux-amd64-21.3.0.tar.gz' | tar xzf - --strip-components=1 -C graalvm
        echo "${PWD}/graalvm/bin" >> $GITHUB_PATH
        echo "JAVA_HOME=${PWD}/graalvm" >> $GITHUB_ENV
    - run: sudo apt-get install -y build-essential libz-dev zlib1g-dev
    - run: |
        echo $LD_LIBRARY_PATH
        sudo ldconfig
    - run: gu install native-image
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build --stacktrace alpha-cli-app:nativeImage -x test
    - run: ./alpha-cli-app/build/native-image/alpha --help
    - run: ./alpha-cli-app/build/native-image/alpha -str 'a.'
    - uses: actions/upload-artifact@v2
      with:
        name: alpha
        path: alpha-cli-app/build/native-image/alpha
