name: Release Alpha

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 0.1.0, 2.1.1, ...)'
        required: true
      next_version:
        description: 'Next version (e.g. 0.2.0, 2.2.0, ...)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # See https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    # See https://github.com/marketplace/actions/gradle-wrapper-validation
    - uses: gradle/wrapper-validation-action@v1
    # See https://github.com/marketplace/actions/setup-java-jdk
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    # See https://github.com/marketplace/actions/gradle-build-action
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.release_version}} -Prelease.newVersion=${{ github.event.inputs.next_version}}-SNAPSHOT

